
wandb:
  run_name: semirapid_probes

default_vehicle_config:
  # The rate of information (i.e., time) is multiplied x 100 for the sake of speeding up the simulation
  mu_anomalies: 0.157
  mu_normal: 0.117
  probe_frequency_seconds: 1


security_manager:
  probe_metrics:
    - RTT
    - INBOUND
    - OUTBOUND