mode: OF

wandb:
  run_name: 10000Hz

default_vehicle_config:
  # The rate of information (i.e., time) is multiplied x 100 for the sake of speeding up the simulation
  mu_anomalies: 0.157
  mu_normal: 0.117


security_manager:
  probe_metrics:
    - RTT
    - INBOUND
    - OUTBOUND

anomaly_detection:
  h_dim: 400
  num_layers: 4
  layer_norm: True


attack:
  automatic_attack_interval_secs: 12
  delay: 0.0001
  target_port: 2181
