
wandb:
  run_name: sudden_mitigation

default_vehicle_config:
  # The rate of information (i.e., time) is multiplied x 100 for the sake of speeding up the simulation
  mu_anomalies: 0.157
  mu_normal: 0.117

default_consumer_config:
  learning_rate: 0.002


security_manager:
  probe_metrics:
    - RTT
    - INBOUND
    - OUTBOUND


anomaly_detection:
  layer_norm: True